# -*- coding: utf-8 -*-
"""task2lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hQQUVjQqrfbUKvjBmbWF_gPKBMWBX4vu
"""

guess = int(input("guess the number which is hidden : "))

answer = 15

if guess >= 1 and guess <=5:
 result = "guess is too low"
 print("your guess "+ result)
elif guess >= 5 and guess <= 10:
  result = " it is close but still low"
  print("your guess "+ result)
elif guess >= 10 and guess <= 15:
   result = "good you have guess right"
   print("your guess "+ result)
elif guess >= 20 :
   result = "too hight"
   print("your guess "+ result)
else :
 print("invalid input")