# -*- coding: utf-8 -*-
"""task3lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hQQUVjQqrfbUKvjBmbWF_gPKBMWBX4vu
"""

from IPython.core.formatters import StringIO
amount = int(input("enter the purchase amount : "))
state = str(input("enter the state name like ( CA, MN, NY) : "))

tax = 0.0

if state == "CA":
 tax = amount * 0.075
 print("the tax charge is  "+ str(tax))
elif state == "MN":
   tax = amount * 0.095
   print("the tax charge is  "+ str(tax))

elif state == "NY":

    tax = amount * 0.089
    print("the tax charge is  "+ str(tax))
else :
 print("invalid input")