# -*- coding: utf-8 -*-
"""task10lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hQQUVjQqrfbUKvjBmbWF_gPKBMWBX4vu
"""

cast = ["Barney Stinson", "Robin Scherbatsky", "Ted Mosby", "Lily Aldrin", "Marshall Eriksen"]
heights = [72, 68, 72, 66, 76]

# Modify the cast list using enumerate() and a for loop
for index, name in enumerate(cast):
    cast[index] = name + str(heights[index])

print(cast)