# -*- coding: utf-8 -*-
"""task8lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hQQUVjQqrfbUKvjBmbWF_gPKBMWBX4vu
"""

scores = {"Usama banglani": 70, "Shahzad Haider": 35, "Eid Muhammad": 82, "awais chandio": 23, "Kantesh Sukhani": 98}

# List comprehension to get names with scores >= 65
passed_names = [name for name, score in scores.items() if score >= 65]

print(passed_names)