# -*- coding: utf-8 -*-
"""task1lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hQQUVjQqrfbUKvjBmbWF_gPKBMWBX4vu
"""

point = int(input("enter the points your have achieved : "))

result = ""

if point >= 1 and point <= 50:
   result = "wooden rabbit"
   print("congratulations you have won : "+ result)
elif point >= 51 and point <= 150:
   result = "no pirze"
   print("congratulations you have won : "+ result)
elif point >= 151 and point <= 180:
   result = "water thin mint"
   print("congratulations you have won : "+ result)
elif point >= 180 and point <= 200:
  result = "penguin"
  print("congratulations you have won : "+ result)
else :
  print("no prize this time")