# -*- coding: utf-8 -*-
"""task4lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hQQUVjQqrfbUKvjBmbWF_gPKBMWBX4vu
"""

sentence = ["the", "quick", "brown", "fox", "jumped", "over", "the", "lazy", "dog"]

for i in sentence:

  print(i)