# -*- coding: utf-8 -*-
"""task5lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hQQUVjQqrfbUKvjBmbWF_gPKBMWBX4vu
"""

for num in range(5, 31, 5):
    print(num)